version: '3'
services:
  web:
    container_name: nlp
    build: .
    image: fumi00hiro/nlp
    working_dir: /nlp
    ports:
      - 8000:8000
      - 8080:8080
    volumes:
      - .:/nlp
    tty: true
